### ISSUE TITLE
unable to start unicorn

### ISSUE THREAD

**Issue by kris-luminar** [bbc/REST-API-example#1]
When I try to start to unicorn server I get stuff like this

```
E, [2013-09-27T11:13:08.147770 #83109] ERROR -- : reaped #<Process::Status: pid 83603 exit 1> worker=0
I, [2013-09-27T11:13:08.148688 #83109]  INFO -- : worker=0 spawning...
I, [2013-09-27T11:13:08.150216 #83604]  INFO -- : worker=0 spawned pid=83604
I, [2013-09-27T11:13:08.150534 #83604]  INFO -- : Refreshing Gem list
config.ru:1:in `require': cannot load such file -- app (LoadError)
        from config.ru:1:in `block in <main>'
```

I think this is weird because`config.ru:1` just requires `app`, which should be able to pull in `app.rb`, which is in the same directory as `config.ru`.
# 

My environment:
-  Mac OS 10.8.5
-  ruby 1.9.3p448 (2013-06-27 revision 41675) [x86_64-darwin12.4.0]
-  rvm 1.21.19 (stable)

**Comment by UnsafePointer** [comment]
I'm having the same problem. Have you resolve this issue?

**Comment by kris-luminar** [comment]
@Ruenzuo nope. I gave up and used a different project.

**Comment by UnsafePointer** [comment]
@kris-luminar I have solved this issue. You can check the pull request #3 and see it that works for you.

**Comment by chrisn** [comment]
@Ruenzuo Thanks for fixing this, we really appreciate it!
